version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: franchise_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: franchise_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
